test

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -52,3 +52,47 @@ jobs:
           
           # Print the formatted content
           cat backend.tf
+
+          - name: 'Terraform Init'
+          working-directory: ./terraform
+          run: terraform init
+    
+      - name: 'Terraform Format Check'
+          working-directory: ./terraform
+          run: |
+            # Run format check
+            terraform fmt -check
+            if [ $? -eq 0 ]; then
+              echo "Formatting check passed"
+            else
+              echo "Formatting issues found"
+              exit 1
+            fi
+    
+      - name: 'Terraform Plan'
+        working-directory: ./terraform
+        run: |
+            set +e
+            terraform plan -detailed-exitcode -out=tfplan > plan_output.txt 2>&1
+            PLAN_EXIT_CODE=$?
+            cat plan_output.txt
+            if [ $PLAN_EXIT_CODE -eq 1 ]; then
+              echo "Terraform plan failed"
+              exit 1
+            fi
+            echo "TERRAFORM_PLAN_EXIT_CODE=$PLAN_EXIT_CODE" >> $GITHUB_ENV
+    
+      - name: 'Terraform Apply'
+        working-directory: ./terraform
+        #if: github.ref == 'refs/heads/main' && env.TERRAFORM_PLAN_EXIT_CODE == 2
+        run: |
+            echo "Applying changes"
+            terraform apply -auto-approve tfplan
+            # Optional: Verify state was created
+        
+      - name: 'Verify State'
+        working-directory: ./terraform
+        if: success() && github.ref == 'refs/heads/main'
+        run: |
+            echo "Verifying state file creation..."
+            terraform state list          
