test

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -15,6 +15,15 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
+    - name: Verify Azure Credentials
+      run: |
+        if [[ -n "${{ secrets.AZURE_CREDENTIALS }}" ]]; then
+          echo "AZURE_CREDENTIALS secret is present"
+        else
+          echo "::error::AZURE_CREDENTIALS secret is missing"
+          exit 1
+        fi
+
     - name: Checkout
       uses: actions/checkout@v4
 
